<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24933" started-at="2014-11-13T08:23:46Z" finished-at="2014-11-13T08:24:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24933" started-at="2014-11-13T08:23:46Z" finished-at="2014-11-13T08:24:11Z">
      <class name="com.crowdtogo.test.apply.CrowdieApplicationStep2">
        <test-method status="FAIL" signature="initialize()[pri:0, instance:com.crowdtogo.test.apply.CrowdieApplicationStep2@10d42d49]" name="initialize" is-config="true" duration-ms="0" started-at="2014-11-13T16:23:46Z" finished-at="2014-11-13T16:23:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.crowdtogo.test.apply.CrowdieApplication.inputApply(CrowdieApplication.java:17)
	at com.crowdtogo.test.apply.CrowdieApplicationStep2.initialize(CrowdieApplicationStep2.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="SKIP" signature="testStep2Valid()[pri:0, instance:com.crowdtogo.test.apply.CrowdieApplicationStep2@10d42d49]" name="testStep2Valid" duration-ms="0" started-at="2014-11-13T16:24:11Z" finished-at="2014-11-13T16:24:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStep2Valid -->
        <test-method status="SKIP" signature="testStep2Valid2()[pri:0, instance:com.crowdtogo.test.apply.CrowdieApplicationStep2@10d42d49]" name="testStep2Valid2" duration-ms="0" started-at="2014-11-13T16:24:11Z" finished-at="2014-11-13T16:24:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStep2Valid2 -->
      </class> <!-- com.crowdtogo.test.apply.CrowdieApplicationStep2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
